server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/com_twt_tlb?serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

twt:
  jwt:
    secret: twt-tlb
    expire: 604800
